// Static data from movies - Fallback when there is an error in server or problems with cors
export const originals = {
  results: [
    {
      backdrop_path: '/b0WmHGc8LHTdGCVzxRb3IBMur57.jpg',
      first_air_date: '2021-03-19',
      id: 88396,
      name: 'Falcão e o Soldado Invernal',
      original_name: 'The Falcon and the Winter Soldier',
      overview:
        'Após os eventos de "Vingadores: Ultimato", Sam Wilson/Falcão e Bucky Barnes/Soldado Invernal se unem em uma aventura que testa suas habilidades - e a paciência.',
      poster_path: '/w8Hi3GI4q1oR6EImrDWrAQFn8Ha.jpg',
      vote_average: 7.9,
    },
    {
      backdrop_path: '/mZjZgY6ObiKtVuKVDrnS9VnuNlE.jpg',
      first_air_date: '2017-09-25',
      id: 71712,
      name: 'The Good Doctor: O Bom Doutor',
      original_name: 'The Good Doctor',
      overview:
        'Um jovem médico com autismo começa a trabalhar em um famoso hospital. Além dos desafios da profissão, ele terá também que provar sua capacidade a seus colegas e superiores.',
      poster_path: '/jtLB7xJKcbekmOYkb5NZditBsgk.jpg',
      vote_average: 8.6,
    },
    {
      backdrop_path: '/jeruqNWhqRqOR1QyqdQdHunrvU5.jpg',
      first_air_date: '2014-10-07',
      id: 60735,
      name: 'Flash',
      original_name: 'The Flash',
      overview:
        'Barry enfrenta diversos assassinos que invadem a premiação onde ele acompanha Iris, mas os efeitos colaterais de seus novos superpoderes representam uma ameaça.',
      poster_path: '/wHa6KOJAoNTFLFtp7wguUJKSnju.jpg',
      vote_average: 7.7,
    },
    {
      backdrop_path: '/6UH52Fmau8RPsMAbQbjwN3wJSCj.jpg',
      first_air_date: '2021-03-26',
      id: 95557,
      name: 'Invencível',
      original_name: 'Invincible',
      overview:
        'exceto que seu pai é o super-herói mais poderoso do planeta, Omni-Man. Porém, à medida que Mark desenvolve seus próprios poderes, ele descobre que o legado de seu pai pode não ser tão heroico quanto parece.',
      poster_path: '/hXWGbKLfARbfFyMCQ90AQRGjEGo.jpg',
      vote_average: 8.9,
    },
    {
      backdrop_path: '/4YKkS95v9o9c0tBVA46xIn6M1tx.jpg',
      first_air_date: '2021-05-07',
      id: 93484,
      name: 'O Legado de Júpiter',
      original_name: "Jupiter's Legacy",
      overview:
        'A primeira geração desses super-heróis manteve o mundo seguro por quase um século. Mas será que seus filhos vão conseguir carregar esse legado?',
      poster_path: '/1RFKW55GHQShX07TdXFHvGFjZKI.jpg',
      vote_average: 7.4,
    },
    {
      backdrop_path: '/edmk8xjGBsYVIf4QtLY9WMaMcXZ.jpg',
      first_air_date: '2005-03-27',
      id: 1416,
      name: "Grey's Anatomy",
      original_name: "Grey's Anatomy",
      overview:
        'Os médicos do Grey Sloan Memorial Hospital lidam diariamente com casos e consequências de vida ou morte. É um no outro que eles encontram apoio, conforto, amizade e, às vezes, até mais que amizade... Juntos, eles descobrem o quanto a vida profissional e a pessoal podem ser complicadas e se misturarem no meio do caminho.',
      poster_path: '/1HAm7sxXu9eGVvs8BIAlkCKGaTd.jpg',
      vote_average: 8.2,
    },
    {
      backdrop_path: '/ta5oblpMlEcIPIS2YGcq9XEkWK2.jpg',
      first_air_date: '2016-01-25',
      id: 63174,
      name: 'Lúcifer',
      original_name: 'Lucifer',
      overview:
        'Entediado com a vida nas trevas, o diabo se muda para Los Angeles, abre um piano-bar e empresta sua sabedoria a uma investigadora de assassinatos.',
      poster_path: '/ulz1G3icgMBMB8Si4AZntnS6VD2.jpg',
      vote_average: 8.5,
    },
    {
      backdrop_path: '/qZtAf4Z1lazGQoYVXiHOrvLr5lI.jpg',
      first_air_date: '2017-01-26',
      id: 69050,
      name: 'Riverdale',
      original_name: 'Riverdale',
      overview:
        'Enquanto tentam lidar com problemas típicos da adolescência como amor, sexo, escola e família, Archie e sua turma se envolvem em um grande mistério.',
      poster_path: '/pHcNHYPg0c2vg7qay6wjJoApUgS.jpg',
      vote_average: 8.6,
    },
    {
      backdrop_path: '/9CDC7ttWhF54dVO7HHitLa4tHnc.jpg',
      first_air_date: '2021-03-24',
      id: 120168,
      name: 'Quem Matou Sara?',
      original_name: '¿Quién mató a Sara?',
      overview:
        'Determinado a se vingar e provar que foi falsamente incriminado pelo assassinato da irmã, Álex está prestes a descobrir muito mais do que o real culpado pelo crime.',
      poster_path: '/5BYyTmEqkYXIgdDPyEiAeAbhIsI.jpg',
      vote_average: 7.8,
    },
    {
      backdrop_path: '/nBrkOZyI75artyizuBFeya48KbO.jpg',
      first_air_date: '2019-03-15',
      id: 86831,
      name: 'Love, Death + Robots',
      original_name: 'Love, Death & Robots',
      overview:
        'Criaturas aterrorizantes, surpresas bizarras e humor ácido. Tudo isso e muito mais nesta série de animação de Tim Miller e David Fincher.',
      poster_path: '/asDqvkE66EegtKJJXIRhBJPxscr.jpg',
      vote_average: 8.2,
    },
    {
      backdrop_path: '/58PON1OrnBiX6CqEHgeWKVwrCn6.jpg',
      first_air_date: '2015-08-23',
      id: 62286,
      name: 'Fear the Walking Dead',
      original_name: 'Fear the Walking Dead',
      overview:
        'Ambientada em Los Angeles, a série mostra o começo do apocalipse zumbi e a temível desintegração da sociedade pelos olhos de uma família disfuncional, que precisa se unir para tentar sobreviver ao caos do fim dos tempos.',
      poster_path: '/tbgPaIEZa9BuKKESdyapOn0CZh6.jpg',
      vote_average: 7.6,
    },
    {
      backdrop_path: '/uro2Khv7JxlzXtLb8tCIbRhkb9E.jpg',
      first_air_date: '2010-10-31',
      id: 1402,
      name: 'The Walking Dead',
      original_name: 'The Walking Dead',
      overview:
        'Nos Estados Unidos pós-apocalíptico, um pequeno grupo de sobreviventes segue viajando à procura de uma nova casa longe dos mortos-vivos. O desespero por segurança e suprimentos os coloca constantemente à beira da sanidade.',
      poster_path: '/reKs8y4mPwPkZG99ZpbKRhBPKsX.jpg',
      vote_average: 8.1,
    },
    {
      backdrop_path: '/1i1N0AVRb54H6ZFPDTwbo9MLxSF.jpg',
      first_air_date: '2021-01-15',
      id: 85271,
      name: 'WandaVision',
      original_name: 'WandaVision',
      overview:
        'Wanda Maximoff  e Visão, um casal de super-heróis com uma vida perfeita, que começa a suspeitar que nem tudo é o que parece.',
      poster_path: '/cm5xwxoWl2ZWuCKzwa0umHHsbmI.jpg',
      vote_average: 8.4,
    },
  ],
}
export const trending = {
  results: [
    {
      backdrop_path: '/6ELCZlTA5lGUops70hKdB83WJxH.jpg',
      id: 460465,
      original_title: 'Mortal Kombat',
      overview:
        'Nova aventura baseada no videogame Mortal Kombat. Na história, um jovem que nunca treinou artes marciais acaba envolvido em um gigantesco torneio de luta envolvendo guerreiros da Terra e lutadores e outras dimensões.',
      poster_path: '/w8BVC3qrCWCiTHRz4Rft12dtQF0.jpg',
      title: 'Mortal Kombat',
      vote_average: 7.6,
    },
    {
      backdrop_path: '/gUttUEqsrvaMlK5oL5TSQ54iE96.jpg',
      id: 520663,
      original_title: 'The Woman in the Window',
      overview:
        'A Dr.ª Anna Fox é uma alcoólatra reclusa que passa os dias em seu apartamento em Nova York assistindo a filmes antigos e observando seus vizinhos. Quando a família Russell se muda para o prédio da frente, ela passa a espionar o que seria a família perfeita, até testemunhar uma cena chocante que muda sua vida.',
      poster_path: '/8BasMP1hUZtDx0khdbHBkVZhKjJ.jpg',
      title: 'A Mulher na Janela',
      vote_average: 6.3,
    },
    {
      backdrop_path: '/ouOojiypBE6CD1aqcHPVq7cJf2R.jpg',
      id: 578701,
      original_title: 'Those Who Wish Me Dead',
      overview:
        'Um adolescente, que é testemunha de um assassinato, passa a ser perseguido por assassinos gêmeos no deserto de Montana, com um especialista em sobrevivência encarregado de protegê-lo. Por outro lado, um incêndio florestal ameaça a consumir todos eles.',
      poster_path: '/lkp6LB2ZfKC4TrGhUJu376PaTFg.jpg',
      title: 'Aqueles Que Me Desejam a Morte',
      vote_average: 7.2,
    },
    {
      backdrop_path: '/jedggylU3FyIN7XRAl9WY8mrT6H.jpg',
      original_title: 'Oxygène',
      poster_path: '/w7pdbDCMdtBq9W2amvUglhgmusW.jpg',
      id: 471498,
      title: 'Oxigênio',
      vote_average: 6.9,
      overview:
        'Uma mulher acorda sem memória dentro de uma cápsula de criogenia. O oxigênio está acabando rapidamente, e ela precisa encontrar uma forma de descobrir quem é para conseguir sobreviver.',
    },
    {
      poster_path: '/uHEZ4ZMziIjlAgCTQAEh9ROvtj0.jpg',
      vote_average: 7.3,
      overview:
        'Um agente da CIA busca vingança depois de sua namorada ter sido morta por um traficante de Baltimore.',
      backdrop_path: '/fPGeS6jgdLovQAKunNHX8l0avCy.jpg',
      title: 'Sem Remorso',
      id: 567189,
      original_title: "Tom Clancy's Without Remorse",
    },
    {
      backdrop_path: '/nBrkOZyI75artyizuBFeya48KbO.jpg',
      first_air_date: '2019-03-15',
      id: 86831,
      name: 'Love, Death + Robots',
      original_name: 'Love, Death & Robots',
      overview:
        'Criaturas aterrorizantes, surpresas bizarras e humor ácido. Tudo isso e muito mais nesta série de animação de Tim Miller e David Fincher.',
      poster_path: '/asDqvkE66EegtKJJXIRhBJPxscr.jpg',
      vote_average: 8.2,
    },
    {
      backdrop_path: '/inJjDhCjfhh3RtrJWBmmDqeuSYC.jpg',
      id: 399566,
      original_title: 'Godzilla vs. Kong',
      overview:
        'Em uma época em que os monstros andam na Terra, a luta da humanidade por seu futuro coloca Godzilla e Kong em rota de colisão que verá as duas forças mais poderosas da natureza no planeta se confrontarem em uma batalha espetacular para as idades. Enquanto Monarch embarca em uma missão perigosa em terreno desconhecido e descobre pistas sobre as origens dos Titãs, uma conspiração humana ameaça tirar as criaturas, boas e más, da face da terra para sempre.',
      poster_path: '/klAIFewuqcyEmH1SMtR2XbMyqzM.jpg',
      title: 'Godzilla vs. Kong',
      vote_average: 8.1,
    },
    {
      original_title: 'The Mitchells vs. The Machines',
      poster_path: '/gmnAu2G9EvHbUYTiT6eNd6XlaBx.jpg',
      id: 501929,
      vote_average: 8.1,
      overview:
        'Katie Mitchell é aceita na faculdade de cinema dos seus sonhos e seu pai decide aproveitar para realizar uma viagem em família para levá-la à universidade. Porém, seus planos são interrompidos por uma revolução robótica e agora os Mitchells terão que unir forças em família para trabalhar juntos para salvar o mundo.',
      backdrop_path: '/egxe0rPverBETHzV6COXFGL4edC.jpg',
      title: 'A Família Mitchell e a Revolta das Máquinas',
    },
    {
      original_name: "Jupiter's Legacy",
      backdrop_path: '/4YKkS95v9o9c0tBVA46xIn6M1tx.jpg',
      first_air_date: '2021-05-07',
      vote_average: 7.4,
      name: 'O Legado de Júpiter',
      poster_path: '/1RFKW55GHQShX07TdXFHvGFjZKI.jpg',
      overview:
        'A primeira geração desses super-heróis manteve o mundo seguro por quase um século. Mas será que seus filhos vão conseguir carregar esse legado?',
      id: 93484,
    },
    {
      original_name: 'The Bad Batch',
      backdrop_path: '/sjxtIUCWR74yPPcZFfTsToepfWm.jpg',
      id: 105971,
      first_air_date: '2021-05-04',
      poster_path: '/mMDYVkdrhTqpLSnmzF4MQ5pmrU4.jpg',
      name: 'Star Wars: The Bad Batch',
      vote_average: 9,
      overview:
        'Os Mal Feitos precisam encontrar seu caminho numa galáxia em rápida transformação.',
    },
    {
      backdrop_path: '/7prYzufdIOy1KCTZKVWpjBFqqNr.jpg',
      id: 527774,
      original_title: 'Raya and the Last Dragon',
      overview:
        'O reino encantado Kumandra é dividido em cinco regiões e sua população venerava os dragões mágicos que eram presentes no reino, porém quando uma força maligna ameaçou a Terra, os dragões se sacrificaram para salvar a humanidade. Agora, 500 anos depois, o mesmo mal voltou e cabe a uma guerreira solitária, Raya, rastrear o lendário último dragão para restaurar a terra fraturada e seu povo dividido.',
      poster_path: '/yXrb84zJidCefyhTWHwo4yCDvwz.jpg',
      title: 'Raya e o Último Dragão',
      vote_average: 8.2,
    },
    {
      original_title: "Zack Snyder's Justice League",
      id: 791373,
      vote_average: 8.5,
      overview:
        'Determinado a garantir que o sacrifício final do Superman não foi em vão, Bruce Wayne alinha forças com Diana Prince com planos de recrutar uma equipe de metahumanos para proteger o mundo de uma ameaça de proporções catastróficas que se aproxima.',
      title: 'Liga da Justiça de Zack Snyder',
      backdrop_path: '/pcDc2WJAYGJTTvRSEIpRZwM3Ola.jpg',
      poster_path: '/ArWn6gCi61b3b3hclD2L0LOk66k.jpg',
    },
    {
      original_title: 'Nobody',
      poster_path: '/woPYFGKwVULILbO7q44HmsNY0kO.jpg',
      vote_average: 8.4,
      overview:
        'Quando dois ladrões invadem sua casa no subúrbio uma noite, Hutch se recusa a defender a si mesmo ou a sua família, na esperança de evitar violência grave. Seu filho adolescente, Blake, está desapontado com ele e sua esposa, Becca, parece se afastar ainda mais.  Em consequência, o incidente acerta a raiva latente de Hutch, desencadeando instintos adormecidos e impulsionando-o em um caminho brutal que revelará segredos obscuros e habilidades letais para salvar sua família.',
      title: 'Anônimo',
      id: 615457,
      backdrop_path: '/6zbKgwgaaCyyBXE4Sun4oWQfQmi.jpg',
    },
    {
      backdrop_path: '/gPKcJzrbgs1670fOeKN1xQH9mNa.jpg',
      id: 823855,
      original_title: 'I Am All Girls',
      overview:
        'Uma detetive implacável se une a uma assassina que ataca os integrantes de uma quadrilha de tráfico de crianças.',
      poster_path: '/gWBXydaQ9vX3OIf0f1wNQ9Z0ElQ.jpg',
      title: 'Eu Sou Todas as Meninas',
      vote_average: 7.1,
    },
    {
      name: 'Falcão e o Soldado Invernal',
      poster_path: '/w8Hi3GI4q1oR6EImrDWrAQFn8Ha.jpg',
      vote_average: 7.9,
      first_air_date: '2021-03-19',
      overview:
        'Após os eventos de "Vingadores: Ultimato", Sam Wilson/Falcão e Bucky Barnes/Soldado Invernal se unem em uma aventura que testa suas habilidades - e a paciência.',
      id: 88396,
      backdrop_path: '/b0WmHGc8LHTdGCVzxRb3IBMur57.jpg',
      original_name: 'The Falcon and the Winter Soldier',
    },
    {
      backdrop_path: '/xPpXYnCWfjkt3zzE0dpCNME1pXF.jpg',
      id: 635302,
      original_title: '劇場版「鬼滅の刃」無限列車編',
      overview:
        'Tanjiro Kamado, junto com Inosuke Hashibira, um garoto criado por javalis que usa uma cabeça de javali, e Zenitsu Agatsuma, um garoto assustado que revela seu verdadeiro poder quando dorme, embarca no Trem Infinito em uma nova missão com o Hashira de Fogo, Kyojuro Rengoku, para derrotar um demônio que tem atormentado o povo e matado os caçadores de oni que se opõem a ele!',
      poster_path: '/m2FNRngyJMyxLatBMJR8pbeG2v.jpg',
      title: 'Demon Slayer - Mugen Train: O Filme',
      vote_average: 8.4,
    },
    {
      backdrop_path: '/gOvUJzah5i3DMf3mGUjqfcP05tp.jpg',
      id: 581734,
      original_title: 'Nomadland',
      overview:
        'Após o colapso econômico de uma cidade na zona rural de Nevada, nos Estados Unidos, Fern, uma mulher de 60 anos, entra em sua van e parte para a estrada, vivendo uma vida fora da sociedade convencional como uma nômade moderna.',
      poster_path: '/589uhtJOujc72fgNl6HcMYJS64D.jpg',
      title: 'Nomadland',
      vote_average: 7.3,
    },
    {
      backdrop_path: '/9ns9463dwOeo1CK1JU2wirL5Yi1.jpg',
      id: 587807,
      original_title: 'Tom & Jerry',
      overview:
        'Um gato de rua chamado Tom é contratado por uma garota chamada Kayla, uma jovem empregada que trabalha em um hotel glamouroso em Nova York, para se livrar de Jerry, um rato travesso que se mudou para o hotel, antes que ele seja a ruína de um importante casamento.',
      poster_path: '/9NvYyM8H6d5KAVGqpyFV9YPO5cU.jpg',
      title: 'Tom & Jerry - O Filme',
      vote_average: 7.3,
    },
    {
      backdrop_path: '/owOBJlzH3j3YHUbr3XqSH10CWzo.jpg',
      original_title: 'Things Heard & Seen',
      poster_path: '/bsxQvbWiBa13Vsas5Sj0JhR73QF.jpg',
      vote_average: 5.8,
      title: 'Vozes e Vultos',
      overview:
        'Depois de trocar a cidade grande pelo interior, uma mulher descobre que seu marido e sua casa nova escondem segredos sinistros.',
      id: 631060,
    },
    {
      backdrop_path: '/8z9qQkx7wA6FXpLV8Tiw9mfsRFK.jpg',
      name: 'Sombra e Ossos',
      original_name: 'Shadow and Bone',
      vote_average: 8.3,
      id: 85720,
      overview:
        'Forças sinistras tramam contra uma jovem militar quando ela revela um poder mágico capaz de unir seu mundo.',
      first_air_date: '2021-04-23',
      poster_path: '/vzKboKry7jmH17GgHnexcWX9HiQ.jpg',
    },
  ],
}
export const toprated = {
  results: [
    {
      backdrop_path: '/gNBCvtYyGPbjPCT1k3MvJuNuXR6.jpg',
      id: 19404,
      original_title: 'दिलवाले दुल्हनिया ले जायेंगे',
      overview:
        'Raj e Simran são dois jovens indianos vivendo em Londres que, acidentalmente, se conhecem durante uma viagem pela Europa. Eles se apaixonam, mas Simran está prometida a um indiano. Raj não desanima e segue seu amor até a Índia, onde os dois tentam convencer a todos que precisam ficar juntos.',
      poster_path: '/2CAL2433ZeIihfX1Hb2139CX0pW.jpg',
      title: 'Dilwale Dulhania Le Jayenge',
      vote_average: 8.7,
    },
    {
      backdrop_path: '/jtAI6OJIWLWiRItNSZoWjrsUtmi.jpg',
      id: 724089,
      original_title: "Gabriel's Inferno Part II",
      overview:
        'O professor Gabriel Emerson finalmente descobre a verdade sobre a identidade de Julia Mitchell, mas sua compreensão chega um momento tarde demais. Julia acabou de esperar que o respeitado especialista em Dante se lembrasse dela e não quer mais nada com ele. Gabriel pode reconquistar seu coração antes que ela encontre o amor nos braços de outra pessoa?',
      poster_path: '/pci1ArYW7oJ2eyTo2NMYEKHHiCP.jpg',
      title: 'O Inferno de Gabriel - Parte 2',
      vote_average: 8.7,
    },
    {
      backdrop_path: '/iNh3BivHyg5sQRPP1KOkzguEX0H.jpg',
      id: 278,
      original_title: 'The Shawshank Redemption',
      overview:
        'Em 1946, Andy Dufresne, um jovem e bem sucedido banqueiro, tem a sua vida radicalmente modificada ao ser condenado por um crime que nunca cometeu, o homicídio de sua esposa e do amante dela. Ele é mandado para uma prisão que é o pesadelo de qualquer detento, a Penitenciária Estadual de Shawshank, no Maine. Lá ele irá cumprir a pena perpétua. Andy logo será apresentado a Warden Norton, o corrupto e cruel agente penitenciário, que usa a Bíblia como arma de controle e ao Capitão Byron Hadley que trata os internos como animais. Andy faz amizade com Ellis Boyd Redding, um prisioneiro que cumpre pena há 20 anos e controla o mercado negro da instituição.',
      poster_path: '/4BSuFpQ2gd2WtO5ZK1fMjaMPMRc.jpg',
      title: 'Um Sonho de Liberdade',
      vote_average: 8.7,
    },
    {
      backdrop_path: '/rSPw7tgCH9c6NqICZef4kZjFOQ5.jpg',
      id: 238,
      original_title: 'The Godfather',
      overview:
        'Uma família mafiosa luta para estabelecer sua supremacia nos Estados Unidos depois da Segunda Guerra Mundial. Uma tentativa de assassinato deixa o chefão Vito Corleone incapacitado e força os filhos Michael e Sonny a assumir os negócios.',
      poster_path: '/oJagOzBu9Rdd9BrciseCm3U3MCU.jpg',
      title: 'O Poderoso Chefão',
      vote_average: 8.7,
    },
    {
      backdrop_path: '/fQq1FWp1rC89xDrRMuyFJdFUdMd.jpg',
      id: 761053,
      original_title: "Gabriel's Inferno Part III",
      overview:
        "A parte final da adaptação para o cinema do romance erótico Gabriel's Inferno, escrito por um autor canadense anônimo sob o pseudônimo de Sylvain Reynard.",
      poster_path: '/fYtHxTxlhzD4QWfEbrC1rypysSD.jpg',
      title: 'O Inferno de Gabriel - Parte 3',
      vote_average: 8.7,
    },
    {
      backdrop_path: '/w2uGvCpMtvRqZg6waC1hvLyZoJa.jpg',
      id: 696374,
      original_title: "Gabriel's Inferno",
      overview:
        'Uma exploração intrigante de sedução, amor proibido e redenção, uma história cativante e apaixonada da fuga de um homem de seu próprio inferno pessoal, enquanto ele tenta ganhar o impossível: perdão e amor.',
      poster_path: '/oyG9TL7FcRP4EZ9Vid6uKzwdndz.jpg',
      title: 'O Inferno de Gabriel',
      vote_average: 8.7,
    },
    {
      backdrop_path: '/loRmRzQXZeqG78TqZuyvSlEQfZb.jpg',
      id: 424,
      original_title: "Schindler's List",
      overview:
        'O alemão Oskar Schindler viu na mão de obra judia uma solução barata e viável para lucrar com negócios durante a guerra. Com sua forte influência dentro do partido nazista, foi fácil conseguir as autorizações e abrir uma fábrica. O que poderia parecer uma atitude de um homem não muito bondoso, transformou-se em um dos maiores casos de amor à vida da História, pois este alemão abdicou de toda sua fortuna para salvar a vida de mais de mil judeus em plena luta contra o extermínio alemão.',
      poster_path: '/bGhhNzJYDsuLruNN5bJ2PvLcMiq.jpg',
      title: 'A Lista de Schindler',
      vote_average: 8.6,
    },
    {
      backdrop_path: '/poec6RqOKY9iSiIUmfyfPfiLtvB.jpg',
      id: 240,
      original_title: 'The Godfather: Part II',
      overview:
        'Após a máfia matar sua família, o jovem Vito foge da sua cidade na Sicília e vai para a América. Vito luta para manter sua família. Ele mata Black Hand Fanucci, que exigia dos comerciantes uma parte dos seus ganhos. Com a morte de Fanucci, o poderio de Vito cresce, mas sua família é o que mais importa para ele. Agora baseado no Lago Tahoe, Michael planeja fazer incursões em Las Vegas e Havana instalando negócios ligados ao lazer, mas descobre que aliados como Hyman Roth estão tentando matá-lo.',
      poster_path: '/yB3AkkGMFplGlnPqQZ38W7bdD10.jpg',
      title: 'O Poderoso Chefão: Parte II',
      vote_average: 8.6,
    },
    {
      backdrop_path: '/dIWwZW7dJJtqC6CgWzYkNVKIUm8.jpg',
      id: 372058,
      original_title: '君の名は。',
      overview:
        'Mitsuha é a filha do prefeito de uma pequena cidade, mas sonha em tentar a sorte em Tóquio. Taki trabalha em um restaurante em Tóquio e deseja largar o seu emprego. Os dois não se conhecem, mas estão conectados pelas imagens de seus sonhos.',
      poster_path: '/vfJFJPepRKapMd5G2ro7klIRysq.jpg',
      title: 'Your Name.',
      vote_average: 8.6,
    },
    {
      backdrop_path: '/Ab8mkHmkYADjU7wQiOkia9BzGvS.jpg',
      id: 129,
      original_title: '千と千尋の神隠し',
      overview:
        'Chihiro e seus pais estão se mudando para uma cidade diferente. A caminho da nova casa, o pai decide pegar um atalho. Eles se deparam com uma mesa repleta de comida, embora ninguém esteja por perto. Chihiro sente o perigo, mas seus pais começam a comer. Quando anoitece, eles se transformam em porcos. Agora, apenas Chihiro pode salvá-los',
      poster_path: '/bNBXskBHOwPSW21o7iT3N8QVg9L.jpg',
      title: 'A Viagem de Chihiro',
      vote_average: 8.5,
    },
    {
      backdrop_path: '/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg',
      id: 496243,
      original_title: '기생충',
      overview:
        'Toda a família de Ki-taek está desempregada, vivendo num porão sujo e apertado. Uma obra do acaso faz com que o filho adolescente da família comece a dar aulas de inglês à garota de uma família rica. Fascinados com a vida luxuosa destas pessoas, pai, mãe, filho e filha bolam um plano para se infiltrarem também na família burguesa, um a um. No entanto, os segredos e mentiras necessários à ascensão social custarão caro a todos.',
      poster_path: '/igw938inb6Fy0YVcwIyxQ7Lu5FO.jpg',
      title: 'Parasita',
      vote_average: 8.5,
    },
    {
      backdrop_path: '/xMIyotorUv2Yz7zpQz2QYc8wkWB.jpg',
      id: 497,
      original_title: 'The Green Mile',
      overview:
        '1935, no corredor da morte de uma prisão sulista. Paul Edgecomb (Tom Hanks) é o chefe de guarda da prisão, que temJohn Coffey (Michael Clarke Duncan) como um de seus prisioneiros. Aos poucos, desenvolve-se entre eles uma relação incomum, baseada na descoberta de que o prisioneiro possui um dom mágico que é, ao mesmo tempo, misterioso e milagroso.',
      poster_path: '/2RKjFMIlb3UmvUtxeM1uzS0WMhG.jpg',
      title: 'À Espera de Um Milagre',
      vote_average: 8.5,
    },
    {
      backdrop_path: '/yeJhRNtE4XW2lOoVVFO9iuDr3AL.jpg',
      id: 441130,
      original_title: 'Wolfwalkers',
      overview:
        'A chegada de um caçador de lobos a uma cidadezinha irlandesa é o começo de uma grande aventura para Robyn, quando ela conhece na floresta uma menina com um estranho dom.',
      poster_path: '/gCa0yDjBb6zHgy2dhbud9mfsTLK.jpg',
      title: 'Wolfwalkers',
      vote_average: 8.5,
    },
    {
      backdrop_path: '/88J6waYVTta8Qz3iX3qUeWNA5d5.jpg',
      id: 447362,
      original_title: 'Life in a Year',
      overview:
        'Daryn (Jaden Smith), um excelente atleta do colégio, estudioso e aspirante a rapper, descobre que sua namorada, Isabelle (Cara Delevingne) está doente de um câncer no ovário. Então, ele decide fazer com que ambos vivam juntos, em um ano, experiências dignas de uma vida inteira.',
      poster_path: '/dfmbwqkalJRfYqFSwNhRn4QYK30.jpg',
      title: 'A Vida em um Ano',
      vote_average: 8.5,
    },
    {
      backdrop_path: '/pcDc2WJAYGJTTvRSEIpRZwM3Ola.jpg',
      id: 791373,
      original_title: "Zack Snyder's Justice League",
      overview:
        'Determinado a garantir que o sacrifício final do Superman não foi em vão, Bruce Wayne alinha forças com Diana Prince com planos de recrutar uma equipe de metahumanos para proteger o mundo de uma ameaça de proporções catastróficas que se aproxima.',
      poster_path: '/ArWn6gCi61b3b3hclD2L0LOk66k.jpg',
      title: 'Liga da Justiça de Zack Snyder',
      vote_average: 8.5,
    },
    {
      backdrop_path: '/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg',
      id: 680,
      original_title: 'Pulp Fiction',
      overview:
        'Os assassinos Vincent e Jules passam por imprevistos ao recuperar uma mala para um mafioso. O boxeador Butch é pago pelo mesmo mafioso para perder uma luta, e a esposa do criminoso fica sob responsabilidade de Vincent por uma noite. Essas histórias se relacionam numa teia repleta de violência.',
      poster_path: '/tptjnB2LDbuUWya9Cx5sQtv5hqb.jpg',
      title: 'Pulp Fiction: Tempo de Violência',
      vote_average: 8.5,
    },
    {
      backdrop_path: '/qqHQsStV6exghCM7zbObuYBiYxw.jpg',
      id: 389,
      original_title: '12 Angry Men',
      overview:
        'Um jovem porto-riquenho é acusado do brutal crime de ter matado o próprio pai. Quando ele vai a julgamento, doze jurados se reúnem para decidir a sentença, levando em conta que o réu deve ser considerado inocente até que se prove o contrário. Onze dos jurados têm plena certeza de que ele é culpado, e votam pela condenação, mas um jurado acha que é melhor investigar mais para que a sentença seja correta. Para isso ele terá que enfrentar diferentes interpretações dos fatos, e a má vontade dos outros jurados, que só querem ir logo para suas casas.',
      poster_path: '/q8RGf4SbVCObCySZ4PIGsn5wFm6.jpg',
      title: '12 Homens e Uma Sentença',
      vote_average: 8.5,
    },
    {
      backdrop_path: '/9guoVF7zayiiUq5ulKQpt375VIy.jpg',
      id: 592350,
      original_title: '僕のヒーローアカデミア THE MOVIE ヒーローズ：ライジング',
      overview:
        'Izuku, Bakugo e o resto dos alunos da Turma A da Academia de Heróis terão que unir forças mais uma vez para enfrentar o vilão, Nine.',
      poster_path: '/Ar8jquseIADaFtMH6dQpskLwDYf.jpg',
      title: 'My Hero Academia: Ascensão dos Heróis',
      vote_average: 8.5,
    },
    {
      backdrop_path: '/uWVkEo9PWHu9algZsiLPi6sRU64.jpg',
      id: 556574,
      original_title: 'Hamilton',
      overview:
        'Hamilton é um musical que conta a história da América por vozes americanas. Por meio da história de um dos principais fundadores americanos e primeiro secretário do Tesouro, Alexander Hamilton, a trilha sonora que mistura hip-hop, jazz, R&B e Broadway revoluciona o teatro no The Richard Rodgers Theatre, na Broadway, em junho de 2016.',
      poster_path: '/h1B7tW0t399VDjAcWJh8m87469b.jpg',
      title: 'Hamilton',
      vote_average: 8.5,
    },
    {
      backdrop_path: '/pm0RiwNpSja8gR0BTWpxo5a9Bbl.jpg',
      id: 122,
      original_title: 'The Lord of the Rings: The Return of the King',
      overview:
        'O confronto final entre as forças do bem e do mal que lutam pelo controle do futuro da Terra Média se aproxima. Sauron planeja um grande ataque a Minas Tirith, capital de Gondor, o que faz com que Gandalf e Pippin partam para o local na intenção de ajudar a resistência. Um exército é reunido por Theoden em Rohan, em mais uma tentativa de deter as forças de Sauron. Enquanto isso, Frodo, Sam e Gollum seguem sua viagem rumo à Montanha da Perdição para destruir o anel.',
      poster_path: '/izPNMzffsgZUvlbiYlPxjFr3TAa.jpg',
      title: 'O Senhor dos Anéis: O Retorno do Rei',
      vote_average: 8.5,
    },
  ],
}
export const action = {
  results: [
    {
      backdrop_path: '/fPGeS6jgdLovQAKunNHX8l0avCy.jpg',
      id: 567189,
      original_title: "Tom Clancy's Without Remorse",
      overview:
        'Um agente da CIA busca vingança depois de sua namorada ter sido morta por um traficante de Baltimore.',
      poster_path: '/uHEZ4ZMziIjlAgCTQAEh9ROvtj0.jpg',
      title: 'Sem Remorso',
      vote_average: 7.3,
      vote_count: 907,
    },
    {
      backdrop_path: '/6ELCZlTA5lGUops70hKdB83WJxH.jpg',
      id: 460465,
      original_title: 'Mortal Kombat',
      overview:
        'Nova aventura baseada no videogame Mortal Kombat. Na história, um jovem que nunca treinou artes marciais acaba envolvido em um gigantesco torneio de luta envolvendo guerreiros da Terra e lutadores e outras dimensões.',
      poster_path: '/w8BVC3qrCWCiTHRz4Rft12dtQF0.jpg',
      title: 'Mortal Kombat',
      vote_average: 7.6,
      vote_count: 2518,
    },
    {
      backdrop_path: '/inJjDhCjfhh3RtrJWBmmDqeuSYC.jpg',
      id: 399566,
      original_title: 'Godzilla vs. Kong',
      overview:
        'Em uma época em que os monstros andam na Terra, a luta da humanidade por seu futuro coloca Godzilla e Kong em rota de colisão que verá as duas forças mais poderosas da natureza no planeta se confrontarem em uma batalha espetacular para as idades. Enquanto Monarch embarca em uma missão perigosa em terreno desconhecido e descobre pistas sobre as origens dos Titãs, uma conspiração humana ameaça tirar as criaturas, boas e más, da face da terra para sempre.',
      poster_path: '/klAIFewuqcyEmH1SMtR2XbMyqzM.jpg',
      title: 'Godzilla vs. Kong',
      vote_average: 8.1,
      vote_count: 5549,
    },
    {
      backdrop_path: '/6zbKgwgaaCyyBXE4Sun4oWQfQmi.jpg',
      id: 615457,
      original_title: 'Nobody',
      overview:
        'Quando dois ladrões invadem sua casa no subúrbio uma noite, Hutch se recusa a defender a si mesmo ou a sua família, na esperança de evitar violência grave. Seu filho adolescente, Blake, está desapontado com ele e sua esposa, Becca, parece se afastar ainda mais.  Em consequência, o incidente acerta a raiva latente de Hutch, desencadeando instintos adormecidos e impulsionando-o em um caminho brutal que revelará segredos obscuros e habilidades letais para salvar sua família.',
      poster_path: '/woPYFGKwVULILbO7q44HmsNY0kO.jpg',
      title: 'Anônimo',
      vote_average: 8.4,
      vote_count: 1523,
    },
    {
      backdrop_path: '/pcDc2WJAYGJTTvRSEIpRZwM3Ola.jpg',
      id: 791373,
      original_title: "Zack Snyder's Justice League",
      overview:
        'Determinado a garantir que o sacrifício final do Superman não foi em vão, Bruce Wayne alinha forças com Diana Prince com planos de recrutar uma equipe de metahumanos para proteger o mundo de uma ameaça de proporções catastróficas que se aproxima.',
      poster_path: '/ArWn6gCi61b3b3hclD2L0LOk66k.jpg',
      title: 'Liga da Justiça de Zack Snyder',
      vote_average: 8.5,
      vote_count: 5452,
    },
    {
      backdrop_path: '/xPpXYnCWfjkt3zzE0dpCNME1pXF.jpg',
      id: 635302,
      original_title: '劇場版「鬼滅の刃」無限列車編',
      overview:
        'Tanjiro Kamado, junto com Inosuke Hashibira, um garoto criado por javalis que usa uma cabeça de javali, e Zenitsu Agatsuma, um garoto assustado que revela seu verdadeiro poder quando dorme, embarca no Trem Infinito em uma nova missão com o Hashira de Fogo, Kyojuro Rengoku, para derrotar um demônio que tem atormentado o povo e matado os caçadores de oni que se opõem a ele!',
      poster_path: '/m2FNRngyJMyxLatBMJR8pbeG2v.jpg',
      title: 'Demon Slayer - Mugen Train: O Filme',
      vote_average: 8.4,
      vote_count: 958,
    },
    {
      backdrop_path: '/mYM8x2Atv4MaLulaV0KVJWI1Djv.jpg',
      id: 804435,
      original_title: 'Vanquish',
      overview:
        'Uma mãe, Victoria, está tentando deixar seu passado sombrio como uma entregadora de drogas russa para trás, mas o policial aposentado Damon força Victoria a cumprir suas ordens, mantendo sua filha como refém.',
      poster_path: '/AoWY1gkcNzabh229Icboa1Ff0BM.jpg',
      title: 'Vanquish',
      vote_average: 6.3,
      vote_count: 90,
    },
    {
      backdrop_path: '/7prYzufdIOy1KCTZKVWpjBFqqNr.jpg',
      id: 527774,
      original_title: 'Raya and the Last Dragon',
      overview:
        'O reino encantado Kumandra é dividido em cinco regiões e sua população venerava os dragões mágicos que eram presentes no reino, porém quando uma força maligna ameaçou a Terra, os dragões se sacrificaram para salvar a humanidade. Agora, 500 anos depois, o mesmo mal voltou e cabe a uma guerreira solitária, Raya, rastrear o lendário último dragão para restaurar a terra fraturada e seu povo dividido.',
      poster_path: '/yXrb84zJidCefyhTWHwo4yCDvwz.jpg',
      title: 'Raya e o Último Dragão',
      vote_average: 8.2,
      vote_count: 2824,
    },
    {
      backdrop_path: '/z7HLq35df6ZpRxdMAE0qE3Ge4SJ.jpg',
      id: 615678,
      original_title: 'Thunder Force',
      overview:
        'Em um mundo cheio de supervilões, duas melhores amigas de infância se reaproximam quando uma delas inventa um tratamento capaz de dar poderes para que protejam a cidade.',
      poster_path: '/Aej7rR73kpAKce6XXBLeqijAwPD.jpg',
      title: 'Esquadrão Trovão',
      vote_average: 5.8,
      vote_count: 572,
    },
    {
      backdrop_path: '/jFINtstDUh0vHOGImpMAmLrPcXy.jpg',
      id: 643586,
      original_title: "Willy's Wonderland",
      overview:
        'Um faxineiro é forçado a passar a noite num bizarro parque de diversões onde terá que lutar para sobreviver contra personagens animatrônicos que ganham vida.',
      poster_path: '/keEnkeAvifw8NSEC4f6WsqeLJgF.jpg',
      title: "Willy's Wonderland",
      vote_average: 6.8,
      vote_count: 211,
    },
    {
      backdrop_path: '/5Zv5KmgZzdIvXz2KC3n0MyecSNL.jpg',
      id: 634528,
      original_title: 'The Marksman',
      overview:
        'Um fazendeiro na fronteira do Arizona se torna o improvável defensor de um jovem mexicano que foge desesperadamente dos assassinos do cartel que o perseguiram até os EUA.',
      poster_path: '/wAJniojhHa4oVKa9AxdNwvpmS74.jpg',
      title: 'Na Mira do Perigo',
      vote_average: 7.4,
      vote_count: 461,
    },
    {
      backdrop_path: '/ovggmAOu1IbPGTQE8lg4lBasNC7.jpg',
      id: 412656,
      original_title: 'Chaos Walking',
      overview:
        'Em um futuro não muito distante, em um mundo onde as mulheres desapareceram e os homens foram afetados pelo “ruído” – uma força que deixa seus pensamentos audíveis – Todd Hewitt encontra Viola, uma jovem misteriosa que aterrissou em seu planeta. Com Viola correndo perigo, Todd jura protegê-la e colocá-la fora de perigo. Para salvá-la, Todd terá que controlar seu “ruído”, descobrir sua própria força e desvendar todos os segredos sombrios que seu planeta e sua comunidade guardam.',
      poster_path: '/7poSpsfrnhxjVN2uRmemd76ASvS.jpg',
      title: 'Mundo em Caos',
      vote_average: 7.1,
      vote_count: 594,
    },
    {
      backdrop_path: '/z8TvnEVRenMSTemxYZwLGqFofgF.jpg',
      id: 458576,
      original_title: 'Monster Hunter',
      overview:
        'Baseado no jogo da Capcom chamado Monster Hunter, a tenente Artemis e seus soldados são transportados para um novo mundo. Lá, eles se envolvem em batalhas imponentes, buscando desesperadamente a sobrevivência contra bestas gigantes portadoras de habilidades surreais.',
      poster_path: '/2QhhILPAv7MKFd1q57ssQeEV2su.jpg',
      title: 'Monster Hunter',
      vote_average: 7.1,
      vote_count: 1645,
    },
    {
      backdrop_path: '/srYya1ZlI97Au4jUYAktDe3avyA.jpg',
      id: 464052,
      original_title: 'Wonder Woman 1984',
      overview:
        'Em 1984, Diana Prince entra em conflito com dois inimigos formidáveis, Maxwell Lord e a Mulher-Leopardo, enquanto reencontra misteriosamente com seu antigo interesse amoroso Steve Trevor.',
      poster_path: '/qDA95ebiy3W3m8hTRB3xZNZVVBM.jpg',
      title: 'Mulher-Maravilha 1984',
      vote_average: 6.7,
      vote_count: 5137,
    },
    {
      backdrop_path: '/ouOojiypBE6CD1aqcHPVq7cJf2R.jpg',
      id: 578701,
      original_title: 'Those Who Wish Me Dead',
      overview:
        'Um adolescente, que é testemunha de um assassinato, passa a ser perseguido por assassinos gêmeos no deserto de Montana, com um especialista em sobrevivência encarregado de protegê-lo. Por outro lado, um incêndio florestal ameaça a consumir todos eles.',
      poster_path: '/lkp6LB2ZfKC4TrGhUJu376PaTFg.jpg',
      title: 'Aqueles Que Me Desejam a Morte',
      vote_average: 7.2,
      vote_count: 172,
    },
    {
      backdrop_path: '/h9DIlghaiTxbQbt1FIwKNbQvEL.jpg',
      id: 581387,
      original_title: '백두산',
      overview:
        'Estagnado desde 1903, a 9000 pés de altitude, um vulcão entra em erupção na Montanha Baekdu, localizada na fronteira entre a China e a Coreia do Norte. Armado com a ameaça de erupções iminentes, uma equipe de profissionais treinados exclusivamente da Coreia do Sul e do Norte se unem. Juntos, eles devem unir forças e tentar evitar um desastre catastrófico que ameaça a Península Coreana.',
      poster_path: '/yCusqunCMU84z32OK0kyZMnTH45.jpg',
      title: 'Alerta Vermelho',
      vote_average: 6.4,
      vote_count: 256,
    },
    {
      backdrop_path: '/lOSdUkGQmbAl5JQ3QoHqBZUbZhC.jpg',
      id: 775996,
      original_title: 'Outside the Wire',
      overview:
        'Em um futuro próximo, um piloto de drone e um androide ultrassecreto trabalham lado a lado no campo de batalha para evitar um ataque nuclear.',
      poster_path: '/vnVQx7MJMwTvqcn5pkYDImxzlMg.jpg',
      title: 'Zona de Combate',
      vote_average: 6.5,
      vote_count: 1079,
    },
    {
      backdrop_path: '/eTgQlyIQH0nA5BsmYpvCzSPAorg.jpg',
      id: 793723,
      original_title: 'Sentinelle',
      overview:
        'Transferida para casa depois de uma missão traumatizante, uma soldado francesa usa suas habilidades letais para caçar o homem que feriu sua irmã.',
      poster_path: '/56Z9eh4k9pzR6Yhy201nq2Qoa0n.jpg',
      title: 'A Sentinela',
      vote_average: 5.9,
      vote_count: 384,
    },
    {
      backdrop_path: '/6TPZSJ06OEXeelx1U1VIAt0j9Ry.jpg',
      id: 587996,
      original_title: 'Bajocero',
      overview:
        'Um ônibus penitenciário é atacado e o policial encarregado tem que enfrentar criminosos dentro e fora do veículo, além de um inimigo silencioso: o frio congelante.',
      poster_path: '/rofFkTuMwwIJpWJVQaTRYqfQuoN.jpg',
      title: 'Abaixo de Zero',
      vote_average: 6.4,
      vote_count: 553,
    },
    {
      backdrop_path: '/y0SiXoTLQp93NbLQ4XhgVz18UAS.jpg',
      id: 663558,
      original_title: '新神榜：哪吒重生',
      overview:
        'Nezha, um fã de corridas que ganha a vida como entregador, encontra velhos inimigos e precisa redescobrir seus poderes para proteger a família e os amigos.',
      poster_path: '/iyOgNaaDX67AUMWlzsGZVO1luoh.jpg',
      title: 'New Gods Nezha Reborn',
      vote_average: 8.7,
      vote_count: 145,
    },
  ],
}
export const documentary = {
  results: [
    {
      backdrop_path: '/xOukYlFEuiY9FZXd5kjWiigjBJA.jpg',
      id: 736604,
      original_title: 'The Boy from Medellín',
      overview:
        'Acompanha J Balvin enquanto ele se prepara para a apresentação mais importante de sua carreira – um show lotado em um estádio na sua cidade natal, Medellín, na Colômbia. Mas, à medida que a apresentação se aproxima, as ruas explodem com a crescente agitação política, forçando o músico vencedor do Grammy Latino a lutar, com sua responsabilidade como artista, por seu país e sua legião de fãs ao redor do mundo.',
      poster_path: '/ffJX00pcQDGvzhz6RSngeYuSb6U.jpg',
      title: 'The Boy from Medellín',
      vote_average: 5.4,
    },
    {
      backdrop_path: '/uO6ZUez70Twan92pqoV60T9kiGH.jpg',
      id: 440249,
      original_title: 'After Porn Ends 2',
      overview: 'emergir com novas carreiras.',
      poster_path: '/rfItXrtDGILwsCdmgVxX79phFuI.jpg',
      title: 'After Porn Ends 2',
      vote_average: 5.3,
    },
    {
      backdrop_path: '/uILX4gGU9OqpndR7JXENn29MoEv.jpg',
      id: 689249,
      original_title: 'La casa de papel: El fenómeno',
      overview:
        'O documentário La Casa de Papel: O Fenômeno traz um olhar sobre o por quê e como o famoso seriado da Netflix provocou uma onda de entusiasmo em todo o mundo por um astuto grupo de ladrões e o professor que comandou toda a operação.',
      poster_path: '/AboUXTrDWEi0PuZUqaft0iwBTm7.jpg',
      title: 'La casa de papel: El fenómeno',
      vote_average: 7.7,
    },
    {
      backdrop_path: '/hl02jzJ80MozdW71Naf5Ee2881n.jpg',
      id: 812031,
      original_title: 'Héroes: silencio y rock & roll',
      overview: 'Documentário sobre a Banda',
      poster_path: '/gshYpoEqTh3N2xMSr0TqCGDuruj.jpg',
      title: 'Héroes del Silencio Barulho e RocknRoll',
      vote_average: 8.7,
    },
    {
      backdrop_path: '/slh9qCbyDcMN2rC9FiueZ6pR2fj.jpg',
      id: 381749,
      original_title: 'Porno & Libertà',
      overview: '',
      poster_path: '/pNuf9wcdZfL252ecHvYzXDVQWFT.jpg',
      title: 'Porno & Libertà',
      vote_average: 5,
    },
    {
      backdrop_path: '/7OlCmUwpJzJepUaOZ0n6oiCbNMP.jpg',
      id: 128748,
      original_title: 'Curse of the Blair Witch',
      overview: '',
      poster_path: '/kTqRbjRIA6B1RbBaoLV098kwtXa.jpg',
      title: 'Curse of the Blair Witch',
      vote_average: 6.3,
    },
    {
      backdrop_path: '/kfLlBmKDLAdTZSpj8bzFEnnVh1c.jpg',
      id: 638566,
      original_title: 'NARUTO to BORUTO The Live 2019',
      overview: '',
      poster_path: '/8OkxtHotJnegiBbWQSz8fD60NEc.jpg',
      title: 'NARUTO to BORUTO The Live 2019',
      vote_average: 7,
    },
    {
      backdrop_path: '/3mzmeYYUENlILaXGzu3Uv7TCT90.jpg',
      id: 439213,
      original_title: 'More Than Miyagi: The Pat Morita Story',
      overview: '',
      poster_path: '/t3BkZXZe6mXz971OsvVh9wHaC53.jpg',
      title: 'More Than Miyagi: The Pat Morita Story',
      vote_average: 6.4,
    },
    {
      backdrop_path: '/4ftNxKONVuvs6189D2VayUq3SFL.jpg',
      id: 511679,
      original_title: 'Héctor El Father: Conocerás la verdad',
      overview: '',
      poster_path: '/tkP0FzEivLxsUYt8BlaL8Sh7ceY.jpg',
      title: 'Héctor El Father: Conocerás la verdad',
      vote_average: 7.6,
    },
    {
      backdrop_path: '/1Gf5YdhlJ1G7Tf7WkSRrs6ssZ3G.jpg',
      id: 24593,
      original_title: 'Thinking XXX',
      overview: '',
      poster_path: '/kqB0fF7VlODmw1exH4iDZHGUiVI.jpg',
      title: 'Thinking XXX',
      vote_average: 4.9,
    },
    {
      backdrop_path: '/pgsxHZO2Tf7nHpRnBoQZitAPguA.jpg',
      id: 774372,
      original_title: 'ariana grande: excuse me, i love you',
      overview:
        'Ariana Grande sobe ao palco em Londres para sua Sweetener World Tour e compartilha uma visão dos bastidores de sua vida nos ensaios e na estrada.',
      poster_path: '/sO7s9SHO7W1thAwkRJGgLso68gZ.jpg',
      title: 'ariana grande: excuse me, i love you',
      vote_average: 8.4,
    },
    {
      backdrop_path: '/4LOxoeZWt5wr9mooxEZRFK96lDd.jpg',
      id: 483898,
      original_title: '50 Greatest Harry Potter Moments',
      overview: '',
      poster_path: '/g1xiBoLD6v3ZaXPa4QtuXiQeYKW.jpg',
      title: '50 Greatest Harry Potter Moments',
      vote_average: 8,
    },
    {
      backdrop_path: '/79er5H44HZTOhz8HmAGSvc3PoLO.jpg',
      id: 779783,
      original_title: 'Soy Luna: El último concierto',
      overview:
        'O elenco de "Sou Luna" se apresenta ao vivo pela última vez no mítico estádio Luna Park em Buenos Aires. Vamos acompanhá-los na intimidade dos bastidores e relembrar a história da série: dos ensaios iniciais, gravações e turnês até esta incrível despedida.',
      poster_path: '/3hYkI1yrfQ1cht5wtXP9BsSyNdU.jpg',
      title: 'Sou Luna: O Último Show',
      vote_average: 8.4,
    },
    {
      backdrop_path: '/cpZH1cytFcftuAgeaEOasL4xK3r.jpg',
      id: 816836,
      original_title: 'Searching for Sheela',
      overview:
        'Jornalistas e fãs aguardam Ma Anand Sheela, a porta-voz do movimento Rajneesh, que regressa à Índia para uma digressão de entrevistas, após décadas no estrangeiro. Veja tudo o que quiser.',
      poster_path: '/4uUmXmS1BNXieflgr884NnjYRFK.jpg',
      title: 'Em busca de Sheela',
      vote_average: 6.7,
    },
    {
      backdrop_path: '/oamFPL6EMqVNCfF152KiMfrWsXp.jpg',
      id: 810731,
      original_title: 'Why Did You Kill Me?',
      overview:
        'Em busca de justiça e vingança, uma família usa as redes sociais para encontrar as pessoas que mataram a filha de 24 anos.',
      poster_path: '/u2eBUmtBLTzb0M2BDxuNqB9trlz.jpg',
      title: 'Por Que Você Me Matou?',
      vote_average: 6.5,
    },
    {
      backdrop_path: '/dZ1sOBUIrgX4iIEKjo6GiQpUMiL.jpg',
      id: 61927,
      original_title: 'Porno Unplugged',
      overview: '',
      poster_path: '/uoQmK7FRXNIQa7sikGg1xM0QaN9.jpg',
      title: 'Porno Unplugged',
      vote_average: 6.2,
    },
    {
      backdrop_path: '/hDyoS3r1QT5AGAa48ipRojU3PH0.jpg',
      id: 812018,
      original_title: 'Our Towns',
      overview: '',
      poster_path: '/yDtLlmNvjJ3GagL9zREZDJmpUX7.jpg',
      title: 'Our Towns',
      vote_average: 0,
    },
    {
      backdrop_path: '/69GY219MYBurtf8joA2okEa3x8I.jpg',
      id: 787923,
      original_title: "Marvel's Behind the Mask",
      overview:
        'Um documentário especial que explora o poder da identidade por trás dos super-heróis icônicos que conhecemos e amamos. Essas criações e histórias lendárias da Marvel não somente refletiram o mundo exterior – elas se tornaram um reflexo de nossas próprias identidades e de quem somos de verdade.',
      poster_path: '/kKAJjnhNfw4uxkHwRfduHHR8EQJ.jpg',
      title: 'Marvel Por Trás da Máscara',
      vote_average: 8,
    },
    {
      backdrop_path: '/t0kHIE4ERtw3h4qwTSmzt5LyhRY.jpg',
      id: 785976,
      original_title: 'Pelé',
      overview:
        'Documentário que retrata a vida de Pelé, da busca pela perfeição à condição de mito. Abrangendo um extraordinário período de 12 anos, a produção mostra como o único jogador a vencer três Copas do Mundo passou de astro do futebol em 1958 a herói nacional em 1970, uma época radical e turbulenta no Brasil.',
      poster_path: '/cVKAep8V6rrFh0IhABC0bkzjwK5.jpg',
      title: 'Pelé',
      vote_average: 7.5,
    },
    {
      backdrop_path: '/mGBmiWmi7JqeTWnrPicRbkXcsuO.jpg',
      id: 410718,
      original_title: 'Before the Flood',
      overview:
        'Um problema de longas datas está se mostrando cada vez mais grave. Mudanças de temperatura, inundações, e outros fenômenos semelhantes têm se tornado cada vez mais comum, e o que tem sido feito na tentativa de amenizar essa situação? É na busca por respostas para essas questões que Leonardo DiCaprio abraça a missão de testemunhar as mudanças climáticas em diversos países, e de uma forma nunca vista antes.',
      poster_path: '/roXAdppky4GRcwCi8JQ9GLhJDoq.jpg',
      title: 'Seremos História?',
      vote_average: 7.8,
    },
  ],
}
export const movieInfo = {
  88396: {
    backdrop_path: '/b0WmHGc8LHTdGCVzxRb3IBMur57.jpg',
    first_air_date: '2021-03-19',
    genres: [
      { id: 10765, name: 'Sci-Fi & Fantasy' },
      { id: 10759, name: 'Action & Adventure' },
      { id: 18, name: 'Drama' },
      { id: 10768, name: 'War & Politics' },
    ],
    id: 88396,
    name: 'Falcão e o Soldado Invernal',
    number_of_seasons: 1,
    original_name: 'The Falcon and the Winter Soldier',
    overview:
      'Após os eventos de "Vingadores: Ultimato", Sam Wilson/Falcão e Bucky Barnes/Soldado Invernal se unem em uma aventura que testa suas habilidades - e a paciência.',
    popularity: 1066.251,
    poster_path: '/w8Hi3GI4q1oR6EImrDWrAQFn8Ha.jpg',
    vote_average: 7.9,
  },
  71712: {
    backdrop_path: '/mZjZgY6ObiKtVuKVDrnS9VnuNlE.jpg',
    first_air_date: '2017-09-25',
    genres: [{ id: 18, name: 'Drama' }],
    id: 71712,
    name: 'The Good Doctor: O Bom Doutor',
    number_of_seasons: 4,
    original_name: 'The Good Doctor',
    overview:
      'Um jovem médico com autismo começa a trabalhar em um famoso hospital. Além dos desafios da profissão, ele terá também que provar sua capacidade a seus colegas e superiores.',
    popularity: 1087.369,
    poster_path: '/jtLB7xJKcbekmOYkb5NZditBsgk.jpg',
    vote_average: 8.6,
  },
  60735: {
    backdrop_path: '/jeruqNWhqRqOR1QyqdQdHunrvU5.jpg',
    first_air_date: '2014-10-07',
    genres: [
      { id: 18, name: 'Drama' },
      { id: 10765, name: 'Sci-Fi & Fantasy' },
    ],
    id: 60735,
    name: 'Flash',
    number_of_seasons: 7,
    original_name: 'The Flash',
    overview:
      'Barry enfrenta diversos assassinos que invadem a premiação onde ele acompanha Iris, mas os efeitos colaterais de seus novos superpoderes representam uma ameaça.',
    popularity: 1135.315,
    poster_path: '/wHa6KOJAoNTFLFtp7wguUJKSnju.jpg',
    vote_average: 7.7,
  },
  95557: {
    backdrop_path: '/6UH52Fmau8RPsMAbQbjwN3wJSCj.jpg',
    first_air_date: '2021-03-26',
    genres: [
      { id: 16, name: 'Animação' },
      { id: 10759, name: 'Action & Adventure' },
      { id: 18, name: 'Drama' },
      { id: 10765, name: 'Sci-Fi & Fantasy' },
    ],
    id: 95557,
    name: 'Invencível',
    number_of_seasons: 1,
    original_name: 'Invincible',
    overview:
      'INVENCÍVEL é uma animação de super-heróis para adultos e conta a história de Mark Grayson, de 17 anos, um cara como qualquer outro de sua idade, exceto que seu pai é o super-herói mais poderoso do planeta, Omni-Man. Porém, à medida que Mark desenvolve seus próprios poderes, ele descobre que o legado de seu pai pode não ser tão heroico quanto parece.',
    popularity: 875.75,
    poster_path: '/hXWGbKLfARbfFyMCQ90AQRGjEGo.jpg',
    vote_average: 8.9,
  },
  93484: {
    backdrop_path: '/4YKkS95v9o9c0tBVA46xIn6M1tx.jpg',
    first_air_date: '2021-05-07',
    genres: [
      { id: 10765, name: 'Sci-Fi & Fantasy' },
      { id: 10759, name: 'Action & Adventure' },
      { id: 18, name: 'Drama' },
      { id: 9648, name: 'Mistério' },
    ],
    id: 93484,
    name: 'O Legado de Júpiter',
    number_of_seasons: 1,
    original_name: "Jupiter's Legacy",
    overview:
      'A primeira geração desses super-heróis manteve o mundo seguro por quase um século. Mas será que seus filhos vão conseguir carregar esse legado?',
    popularity: 794.23,
    poster_path: '/1RFKW55GHQShX07TdXFHvGFjZKI.jpg',
    vote_average: 7.4,
  },
  1416: {
    backdrop_path: '/edmk8xjGBsYVIf4QtLY9WMaMcXZ.jpg',
    first_air_date: '2005-03-27',
    genres: [{ id: 18, name: 'Drama' }],
    id: 1416,
    name: "Grey's Anatomy",
    number_of_seasons: 17,
    original_name: "Grey's Anatomy",
    overview:
      'Os médicos do Grey Sloan Memorial Hospital lidam diariamente com casos e consequências de vida ou morte. É um no outro que eles encontram apoio, conforto, amizade e, às vezes, até mais que amizade... Juntos, eles descobrem o quanto a vida profissional e a pessoal podem ser complicadas e se misturarem no meio do caminho.',
    popularity: 770.248,
    poster_path: '/1HAm7sxXu9eGVvs8BIAlkCKGaTd.jpg',
    vote_average: 8.2,
  },
  63174: {
    backdrop_path: '/ta5oblpMlEcIPIS2YGcq9XEkWK2.jpg',
    first_air_date: '2016-01-25',
    genres: [
      { id: 80, name: 'Crime' },
      { id: 10765, name: 'Sci-Fi & Fantasy' },
    ],
    id: 63174,
    name: 'Lúcifer',
    number_of_seasons: 6,
    original_name: 'Lucifer',
    overview:
      'Entediado com a vida nas trevas, o diabo se muda para Los Angeles, abre um piano-bar e empresta sua sabedoria a uma investigadora de assassinatos.',
    popularity: 677.183,
    poster_path: '/ulz1G3icgMBMB8Si4AZntnS6VD2.jpg',
    vote_average: 8.5,
  },
  69050: {
    backdrop_path: '/qZtAf4Z1lazGQoYVXiHOrvLr5lI.jpg',
    first_air_date: '2017-01-26',
    genres: [
      { id: 9648, name: 'Mistério' },
      { id: 18, name: 'Drama' },
      { id: 80, name: 'Crime' },
    ],
    id: 69050,
    name: 'Riverdale',
    number_of_seasons: 5,
    original_name: 'Riverdale',
    overview:
      'Enquanto tentam lidar com problemas típicos da adolescência como amor, sexo, escola e família, Archie e sua turma se envolvem em um grande mistério.',
    popularity: 663.729,
    poster_path: '/pHcNHYPg0c2vg7qay6wjJoApUgS.jpg',
    vote_average: 8.6,
  },
  120168: {
    backdrop_path: '/9CDC7ttWhF54dVO7HHitLa4tHnc.jpg',
    first_air_date: '2021-03-24',
    genres: [
      { id: 18, name: 'Drama' },
      { id: 80, name: 'Crime' },
      { id: 9648, name: 'Mistério' },
    ],
    id: 120168,
    name: 'Quem Matou Sara?',
    number_of_seasons: 2,
    original_name: '¿Quién mató a Sara?',
    overview:
      'Determinado a se vingar e provar que foi falsamente incriminado pelo assassinato da irmã, Álex está prestes a descobrir muito mais do que o real culpado pelo crime.',
    popularity: 779.418,
    poster_path: '/5BYyTmEqkYXIgdDPyEiAeAbhIsI.jpg',
    vote_average: 7.8,
  },
  86831: {
    backdrop_path: '/nBrkOZyI75artyizuBFeya48KbO.jpg',
    first_air_date: '2019-03-15',
    genres: [
      { id: 16, name: 'Animação' },
      { id: 10765, name: 'Sci-Fi & Fantasy' },
    ],
    id: 86831,
    name: 'Love, Death + Robots',
    number_of_seasons: 2,
    original_name: 'Love, Death & Robots',
    overview:
      'Criaturas aterrorizantes, surpresas bizarras e humor ácido. Tudo isso e muito mais nesta série de animação de Tim Miller e David Fincher.',
    popularity: 758.649,
    poster_path: '/asDqvkE66EegtKJJXIRhBJPxscr.jpg',
    vote_average: 8.2,
  },
  62286: {
    backdrop_path: '/58PON1OrnBiX6CqEHgeWKVwrCn6.jpg',
    first_air_date: '2015-08-23',
    genres: [
      { id: 10759, name: 'Action & Adventure' },
      { id: 18, name: 'Drama' },
    ],
    id: 62286,
    name: 'Fear the Walking Dead',
    number_of_seasons: 6,
    original_name: 'Fear the Walking Dead',
    overview:
      'Ambientada em Los Angeles, a série mostra o começo do apocalipse zumbi e a temível desintegração da sociedade pelos olhos de uma família disfuncional, que precisa se unir para tentar sobreviver ao caos do fim dos tempos.',
    popularity: 478.998,
    poster_path: '/tbgPaIEZa9BuKKESdyapOn0CZh6.jpg',
    vote_average: 7.6,
  },
  1402: {
    backdrop_path: '/uro2Khv7JxlzXtLb8tCIbRhkb9E.jpg',
    first_air_date: '2010-10-31',
    genres: [
      { id: 10759, name: 'Action & Adventure' },
      { id: 18, name: 'Drama' },
      { id: 10765, name: 'Sci-Fi & Fantasy' },
    ],
    id: 1402,
    name: 'The Walking Dead',
    number_of_seasons: 11,
    original_name: 'The Walking Dead',
    overview:
      'Nos Estados Unidos pós-apocalíptico, um pequeno grupo de sobreviventes segue viajando à procura de uma nova casa longe dos mortos-vivos. O desespero por segurança e suprimentos os coloca constantemente à beira da sanidade.',
    popularity: 420.705,
    poster_path: '/reKs8y4mPwPkZG99ZpbKRhBPKsX.jpg',
    vote_average: 8.1,
  },
  85271: {
    backdrop_path: '/1i1N0AVRb54H6ZFPDTwbo9MLxSF.jpg',
    first_air_date: '2021-01-15',
    genres: [
      { id: 10765, name: 'Sci-Fi & Fantasy' },
      { id: 9648, name: 'Mistério' },
      { id: 18, name: 'Drama' },
    ],
    id: 85271,
    name: 'WandaVision',
    number_of_seasons: 1,
    original_name: 'WandaVision',
    overview:
      'Wanda Maximoff  e Visão, um casal de super-heróis com uma vida perfeita, que começa a suspeitar que nem tudo é o que parece.',
    popularity: 408.972,
    poster_path: '/cm5xwxoWl2ZWuCKzwa0umHHsbmI.jpg',
    vote_average: 8.4,
  },
}
